# config.yml
model:
  teacher:
    name: "custom_teacher"  # Example teacher model (ensure pretrained weights exist)
    pretrained: true
    args:
      num_classes: 1  # Adjust for depth estimation output
  student:
    name: "custom_teacher"  # Lightweight student model
    pretrained: true
    args:
      num_classes: 1

data:
  train:
    dataset: "custom_dataset"  # Define your dataset class for unlabeled images
    root: "/content/drive/MyDrive/images"
    transform:
      - name: "Resize"
      - name: "ToTensor"
      - name: "Normalize"
        args:
          size: (384, 384)
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

distillation:
  forward_proc:
    name: "default_forward"
  loss:
    - name: "mse"  # Mean Squared Error for depth regression
      weight: 0.7
  student_module: "student_output"  # Student model output module
  teacher_module: "teacher_output"  # Teacher model output module
  transform:
    teacher:
      - name: "Identity"  # No transformation needed for depth maps
    student:
      - name: "Identity"

optim:
  epochs: 25
  batch_size: 5
  optimizer:
    name: "Adam"
    args:
      lr: 1e-3
  scheduler:
    name: "StepLR"
    args:
      step_size: 10
      gamma: 0.1

output_dir: "./outputs"